/* eslint-disable */
// Generated by Wrangler by running `wrangler types --include-runtime=false` (hash: e89dae741d8b0b900943585fc0270349)
interface __BaseEnv_Env {
	DB: D1Database;
	PUBLISHER_KEY_ID: "publisher-v1";
	PUBLISHER_HMAC_SECRET: string;
}
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./src/worker/index");
	}
	interface Env extends __BaseEnv_Env {}
}
interface Env extends __BaseEnv_Env {}
type StringifyValues<EnvType extends Record<string, unknown>> = {
	[Binding in keyof EnvType]: EnvType[Binding] extends string ? EnvType[Binding] : string;
};
declare namespace NodeJS {
	interface ProcessEnv extends StringifyValues<Pick<Cloudflare.Env, "PUBLISHER_KEY_ID" | "PUBLISHER_HMAC_SECRET">> {}
}
