/* eslint-disable */
// Generated by Wrangler by running `wrangler types --include-runtime=false` (hash: a87800e9e628a2358bcd833e6a5d37c9)
interface __BaseEnv_Env {
	PUBLISHER_KEY_ID: "publisher-v1";
	PUBLISHER_HMAC_SECRET: string;
}
declare namespace Cloudflare {
	interface Env extends __BaseEnv_Env {}
}
interface Env extends __BaseEnv_Env {}
type StringifyValues<EnvType extends Record<string, unknown>> = {
	[Binding in keyof EnvType]: EnvType[Binding] extends string ? EnvType[Binding] : string;
};
declare namespace NodeJS {
	interface ProcessEnv extends StringifyValues<Pick<Cloudflare.Env, "PUBLISHER_KEY_ID" | "PUBLISHER_HMAC_SECRET">> {}
}
