import type { RunUpload } from "./run.js";

export function createRunFixture(): RunUpload {
  return {
    schemaVersion: 1,
    runId: "01900000-0000-7000-8000-000000000001",
    suiteVersion: "1.0.0",
    protocolVersion: "1.0.0",
    runnerVersion: "0.1.0",
    codexCliVersion: "0.1.0",
    startedAt: "2026-07-16T08:00:00.000Z",
    endedAt: "2026-07-16T08:01:00.000Z",
    mode: "smoke",
    seed: 42,
    status: "completed",
    prompt: {
      id: "codexspeed-prompt-v1",
      sha256: "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa",
    },
    environment: {
      osFamily: "macos",
      osVersion: "15.5",
      architecture: "arm64",
      region: "east-asia",
      authChannel: "chatgpt",
      serviceTier: "default",
    },
    catalog: {
      models: [
        {
          id: "gpt-5.3-codex",
          displayName: "GPT-5.3 Codex",
          hidden: false,
          defaultEffort: "medium",
          supportedEfforts: ["low", "medium", "high"],
        },
      ],
    },
    selection: {
      cells: [{ model: "gpt-5.3-codex", effort: "medium" }],
      warmupPerModel: 0,
      measuredRounds: 1,
      maxTurns: 2,
    },
    samples: [
      {
        sampleId: "01900000-0000-7000-8000-000000000002",
        model: "gpt-5.3-codex",
        effort: "medium",
        phase: "measured",
        round: 1,
        attempt: 1,
        status: "completed",
        firstVisibleTextMs: 1_000,
        lastVisibleTextMs: 11_000,
        totalLatencyMs: 12_500,
        outputTokens: 600,
        reasoningOutputTokens: 100,
        agentMessageCount: 1,
        toolEventCount: 0,
        reroutedTo: null,
        validatorPassed: true,
        validatorReason: "ok",
        errorCode: null,
      },
      {
        sampleId: "01900000-0000-7000-8000-000000000003",
        model: "gpt-5.3-codex",
        effort: "medium",
        phase: "measured",
        round: 1,
        attempt: 2,
        status: "completed",
        firstVisibleTextMs: 900,
        lastVisibleTextMs: 10_900,
        totalLatencyMs: 12_000,
        outputTokens: 600,
        reasoningOutputTokens: 100,
        agentMessageCount: 1,
        toolEventCount: 1,
        reroutedTo: null,
        validatorPassed: true,
        validatorReason: "ok",
        errorCode: null,
      },
    ],
  };
}
